before_script:
- make prepare

stages:
- test

.test_template: &test_definition
  stage: test
  script:
  - haxe -version
  - make test

test-3.1:
  <<: *test_definition
  image: demurgos/haxe@sha256:d85d327756e486f1ee556db9caa3f949619f1e9f89f237661418797b6412e4e0

test-3.4:
  <<: *test_definition
  image: demurgos/haxe@sha256:2b768a04bb0fab09e9075beac303f926ad9f30243bd35e3587e3dc3e5b0b7983
